function hashPassword_(password, salt) {
  var bytes = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, String(salt)+'|'+String(password), Utilities.Charset.UTF_8);
  var hash = bytes.map(function(b){var x=b<0?b+256:b;return ('0'+x.toString(16)).slice(-2);}).join('');
  for(var i=1;i<APP_CONFIG.PASSWORD_ITERATIONS;i++){
    bytes=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, hash, Utilities.Charset.UTF_8);
    hash=bytes.map(function(b){var x=b<0?b+256:b;return ('0'+x.toString(16)).slice(-2);}).join('');
  }
  return hash;
}
function createPasswordRecord_(password){var salt=Utilities.getUuid().replace(/-/g,'');return {salt:salt,hash:hashPassword_(password,salt)};}
function getSession_(token){if(!token)return null;var raw=CacheService.getScriptCache().get('SESSION:'+token);if(!raw)return null;try{return JSON.parse(raw);}catch(e){return null;}}
function createSession_(user){var token=Utilities.getUuid().replace(/-/g,'')+Utilities.getUuid().replace(/-/g,'');var session={token:token,userId:user.userId,loginName:user.loginName,role:user.role,fullName:user.fullName,createdAt:now_().toISOString(),expiresAt:Date.now()+APP_CONFIG.SESSION_TTL_SECONDS*1000};CacheService.getScriptCache().put('SESSION:'+token,JSON.stringify(session),APP_CONFIG.SESSION_TTL_SECONDS);return session;}
function requireSession_(token){var s=getSession_(token);if(!s||s.expiresAt<Date.now())throw new Error('AUTH_REQUIRED');return s;}
function hasPermission_(role,permission){var p=ROLE_PERMISSIONS[role]||[];return p.indexOf('*')>=0||p.indexOf(permission)>=0;}
function requirePermission_(token,permission){var session=requireSession_(token);if(!hasPermission_(session.role,permission))throw new Error('FORBIDDEN');return session;}
function loginUser(payload){try{ensureInitialized_();var login=safeText_(payload.loginName,60);var password=String(payload.password||'');var users=getRows_(SHEETS.USERS,USER_FIELDS);var user=users.filter(function(u){return String(u.loginName).toLowerCase()===login.toLowerCase()&&String(u.status||'ACTIVE')==='ACTIVE';})[0];if(!user)return fail_('INVALID_LOGIN','Tài khoản hoặc mật khẩu không đúng.');var rec=JSON.parse(String(user.passwordRecord||'{}'));if(!rec.salt||hashPassword_(password,rec.salt)!==rec.hash)return fail_('INVALID_LOGIN','Tài khoản hoặc mật khẩu không đúng.');var session=createSession_(user);updateRowById_(SHEETS.USERS,'userId',user.userId,USER_FIELDS,{lastLoginAt:now_(),mustChangePassword:user.mustChangePassword});audit_(user.userId,'LOGIN','USER',user.userId,'SESSION',{});return ok_({session:session,user:{userId:user.userId,fullName:user.fullName,role:user.role,loginName:user.loginName,mustChangePassword:String(user.mustChangePassword)==='true'}},'Đăng nhập thành công.');}catch(e){return errorResponse_(e);}}
function changeOwnPassword(payload){try{var s=requireSession_(payload.token);var old=String(payload.oldPassword||''), np=String(payload.newPassword||'');if(np.length<8)return fail_('WEAK_PASSWORD','Mật khẩu mới phải có ít nhất 8 ký tự.');var user=findRowById_(SHEETS.USERS,'userId',s.userId,USER_FIELDS);var rec=JSON.parse(String(user.passwordRecord||'{}'));if(hashPassword_(old,rec.salt)!==rec.hash)return fail_('INVALID_PASSWORD','Mật khẩu hiện tại không đúng.');var n=createPasswordRecord_(np);updateRowById_(SHEETS.USERS,'userId',s.userId,USER_FIELDS,{passwordRecord:JSON.stringify(n),mustChangePassword:false});audit_(s.userId,'CHANGE_PASSWORD','USER',s.userId,'SESSION',{});return ok_(null,'Đổi mật khẩu thành công.');}catch(e){return errorResponse_(e);}}
function logoutUser(payload){try{var s=getSession_(payload.token);if(s){CacheService.getScriptCache().remove('SESSION:'+s.token);audit_(s.userId,'LOGOUT','USER',s.userId,'SESSION',{});}return ok_(null,'Đã đăng xuất.');}catch(e){return errorResponse_(e);}}
