function setupSystem(){var lock=LockService.getScriptLock();lock.waitLock(30000);try{var props=PropertiesService.getScriptProperties(),ssId=props.getProperty('DB_SPREADSHEET_ID'),ss=ssId?SpreadsheetApp.openById(ssId):SpreadsheetApp.create(APP_CONFIG.SPREADSHEET_NAME);props.setProperty('DB_SPREADSHEET_ID',ss.getId());ensureSheet_(ss,SHEETS.CASES,CASE_FIELDS);ensureSheet_(ss,SHEETS.USERS,USER_FIELDS);ensureSheet_(ss,SHEETS.PROCESS_HISTORY,HISTORY_FIELDS);ensureSheet_(ss,SHEETS.LEGAL_RULES,RULE_FIELDS);ensureSheet_(ss,SHEETS.ATTACHMENTS,ATTACHMENT_FIELDS);ensureSheet_(ss,SHEETS.AUDIT_LOG,AUDIT_FIELDS);ensureSheet_(ss,SHEETS.NOTIFICATIONS,NOTIFICATION_FIELDS);ensureSheet_(ss,SHEETS.SYSTEM_CONFIG,CONFIG_FIELDS);var folderId=props.getProperty('ROOT_FOLDER_ID');if(!folderId){var root=DriveApp.createFolder(APP_CONFIG.ROOT_FOLDER_NAME);folderId=root.getId();props.setProperty('ROOT_FOLDER_ID',folderId);}seedConfig_();seedRules_();seedAdmin_();createTriggers_();if(APP_CONFIG.DEMO_DATA)setupDemoData();return ok_({spreadsheetId:ss.getId(),spreadsheetUrl:ss.getUrl(),rootFolderId:folderId},'Cài đặt hệ thống hoàn tất.');}catch(e){return errorResponse_(e);}finally{lock.releaseLock();}}
function ensureInitialized_(){if(!PropertiesService.getScriptProperties().getProperty('DB_SPREADSHEET_ID'))throw new Error('DATABASE_NOT_INITIALIZED');}
function seedConfig_(){var s=sheet_(SHEETS.SYSTEM_CONFIG);if(s.getLastRow()>1)return;var data=[['APP_NAME',APP_CONFIG.APP_NAME,'Tên hệ thống'],['ORG_NAME',APP_CONFIG.ORG_NAME,'Đơn vị'],['ADDRESS',APP_CONFIG.ADDRESS,'Địa chỉ'],['DUTY_PHONE',APP_CONFIG.DUTY_PHONE,'Số trực ban'],['ALERT_EMAIL',APP_CONFIG.ALERT_EMAIL,'Email cảnh báo'],['VILLAGES',VILLAGES.join('|'),'11 thôn'],['MAX_FILE_BYTES',String(APP_CONFIG.MAX_FILE_BYTES),'Dung lượng/file']];s.getRange(2,1,data.length,3).setValues(data);}
function seedRules_(){var s=sheet_(SHEETS.LEGAL_RULES);if(s.getLastRow()>1)return;var rows=[];CATEGORIES.forEach(function(c){PRIORITIES.forEach(function(p){rows.push([uuid_('RULE'),c.value,p.value,p.value==='CRITICAL'?1:(p.value==='URGENT'?3:7),'Tiếp nhận;phân loại;theo dõi deadline','ACTIVE']);});});s.getRange(2,1,rows.length,RULE_FIELDS.length).setValues(rows);}
function getLegalRule_(category,priority){var rows=getRows_(SHEETS.LEGAL_RULES,RULE_FIELDS);return rows.filter(function(r){return r.category===category&&r.priority===priority&&String(r.active)!=='INACTIVE';})[0]||null;}
function seedAdmin_(){var users=getRows_(SHEETS.USERS,USER_FIELDS);if(users.some(function(u){return u.loginName===APP_CONFIG.ADMIN_LOGIN;}))return;var rec=createPasswordRecord_(APP_CONFIG.ADMIN_DEFAULT_PASSWORD);appendRow_(SHEETS.USERS,USER_FIELDS,{userId:'USR-SUPERADMIN',email:APP_CONFIG.ALERT_EMAIL,fullName:'Quản trị hệ thống',loginName:APP_CONFIG.ADMIN_LOGIN,role:ROLES.SUPER_ADMIN,department:APP_CONFIG.ORG_NAME,villages:VILLAGES.join(','),status:'ACTIVE',mustChangePassword:true,createdAt:now_(),lastLoginAt:'',passwordRecord:JSON.stringify(rec)});}
function createCaseFolder_(caseId){var root=getRootFolder_(),year=Utilities.formatDate(now_(),APP_CONFIG.TIMEZONE,'yyyy'),yearFolder;var it=root.getFoldersByName(year);yearFolder=it.hasNext()?it.next():root.createFolder(year);return yearFolder.createFolder(caseId);}
function saveAttachments_(caseId,folder,files,uploadedBy){files.forEach(function(f){var bytes=Utilities.base64Decode(f.data);if(bytes.length>APP_CONFIG.MAX_FILE_BYTES)throw new Error('FILE_SIZE_NOT_ALLOWED');var blob=Utilities.newBlob(bytes,f.mimeType,f.name);var file=folder.createFile(blob);appendRow_(SHEETS.ATTACHMENTS,ATTACHMENT_FIELDS,{attachmentId:uuid_('ATT'),caseId:caseId,fileName:f.name,mimeType:f.mimeType,size:bytes.length,driveFileId:file.getId(),uploadedAt:now_(),uploadedBy:uploadedBy});});}
function createTriggers_(){ScriptApp.getProjectTriggers().forEach(function(t){var h=t.getHandlerFunction();if(['runDeadlineCheck','sendQueuedNotifications'].indexOf(h)>=0)ScriptApp.deleteTrigger(t);});ScriptApp.newTrigger('runDeadlineCheck').timeBased().everyHours(1).create();ScriptApp.newTrigger('sendQueuedNotifications').timeBased().everyMinutes(10).create();}
